import { Tool } from "@/types/tool";
import { buildImageIntro, buildImageContentSections, buildImageTips, buildImageFaq } from "@/lib/toolContent";

function imgTool(
  overrides: Pick<
    Tool,
    | "slug"
    | "title"
    | "navLabel"
    | "acceptedFileTypes"
    | "acceptedMime"
    | "defaultTargetSize"
    | "defaultTargetUnit"
    | "relatedSlugs"
  > & { outputFormat?: Tool["outputFormat"]; formatWord: string; extraFaq?: Tool["faq"] }
): Tool {
  const label =
    overrides.defaultTargetUnit === "MB"
      ? `${overrides.defaultTargetSize} MB`
      : `${overrides.defaultTargetSize} KB`;
  const sizeKB =
    overrides.defaultTargetUnit === "MB"
      ? (overrides.defaultTargetSize || 1) * 1024
      : overrides.defaultTargetSize || 100;
  const input = { label, sizeKB, formatWord: overrides.formatWord };
  return {
    slug: overrides.slug,
    title: overrides.title,
    navLabel: overrides.navLabel,
    category: "image-compress",
    engine: "image-target-size",
    acceptedFileTypes: overrides.acceptedFileTypes,
    acceptedMime: overrides.acceptedMime,
    outputFormat: overrides.outputFormat || "keep",
    defaultTargetSize: overrides.defaultTargetSize,
    defaultTargetUnit: overrides.defaultTargetUnit,
    allowCustomTarget: true,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: `${overrides.title} Online Free | SizeSnap`,
    metaDescription: `${overrides.title.replace(" Online", "")} for free in your browser. Fast, private, no upload required. Preview before you download.`,
    intro: buildImageIntro(input),
    contentSections: buildImageContentSections(input),
    tips: buildImageTips(input),
    faq: [...buildImageFaq(input), ...(overrides.extraFaq || [])],
    relatedSlugs: overrides.relatedSlugs,
  };
}

const IMG_TYPES = [".jpg", ".jpeg", ".png", ".webp"];
const IMG_MIME = ["image/jpeg", "image/png", "image/webp"];
const JPG_TYPES = [".jpg", ".jpeg"];
const JPG_MIME = ["image/jpeg"];
const PNG_TYPES = [".png"];
const PNG_MIME = ["image/png"];

export const tools: Tool[] = [
  // ---------------- IMAGE COMPRESSION (target size) ----------------
  imgTool({
    slug: "compress-image-to-20kb",
    title: "Compress Image to 20 KB",
    navLabel: "Image to 20 KB",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    defaultTargetSize: 20,
    defaultTargetUnit: "KB",
    formatWord: "Image",
    relatedSlugs: ["compress-image-to-50kb", "compress-image-to-100kb", "compress-jpg-to-20kb", "compress-signature-to-20kb", "image-resizer"],
  }),
  imgTool({
    slug: "compress-image-to-50kb",
    title: "Compress Image to 50 KB",
    navLabel: "Image to 50 KB",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    defaultTargetSize: 50,
    defaultTargetUnit: "KB",
    formatWord: "Image",
    relatedSlugs: ["compress-image-to-20kb", "compress-image-to-100kb", "compress-jpg-to-50kb", "compress-passport-photo-to-50kb", "image-resizer"],
  }),
  imgTool({
    slug: "compress-image-to-100kb",
    title: "Compress Image to 100 KB",
    navLabel: "Image to 100 KB",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    defaultTargetSize: 100,
    defaultTargetUnit: "KB",
    formatWord: "Image",
    relatedSlugs: ["compress-image-to-50kb", "compress-image-to-200kb", "compress-jpg-to-100kb", "compress-png-to-100kb", "image-resizer"],
  }),
  imgTool({
    slug: "compress-image-to-200kb",
    title: "Compress Image to 200 KB",
    navLabel: "Image to 200 KB",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    defaultTargetSize: 200,
    defaultTargetUnit: "KB",
    formatWord: "Image",
    relatedSlugs: ["compress-image-to-100kb", "compress-image-to-500kb", "compress-image-to-custom-size", "image-resizer"],
  }),
  imgTool({
    slug: "compress-image-to-500kb",
    title: "Compress Image to 500 KB",
    navLabel: "Image to 500 KB",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    defaultTargetSize: 500,
    defaultTargetUnit: "KB",
    formatWord: "Image",
    relatedSlugs: ["compress-image-to-200kb", "compress-image-to-1mb", "compress-image-to-custom-size", "image-resizer"],
  }),
  imgTool({
    slug: "compress-image-to-1mb",
    title: "Compress Image to 1 MB",
    navLabel: "Image to 1 MB",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    defaultTargetSize: 1,
    defaultTargetUnit: "MB",
    formatWord: "Image",
    relatedSlugs: ["compress-image-to-500kb", "compress-image-to-custom-size", "image-resizer", "compress-pdf-to-1mb"],
  }),
  imgTool({
    slug: "compress-jpg-to-20kb",
    title: "Compress JPG to 20 KB",
    navLabel: "JPG to 20 KB",
    acceptedFileTypes: JPG_TYPES,
    acceptedMime: JPG_MIME,
    outputFormat: "jpeg",
    defaultTargetSize: 20,
    defaultTargetUnit: "KB",
    formatWord: "JPG",
    relatedSlugs: ["compress-jpg-to-50kb", "compress-image-to-20kb", "compress-signature-to-20kb", "jpg-to-png"],
  }),
  imgTool({
    slug: "compress-jpg-to-50kb",
    title: "Compress JPG to 50 KB",
    navLabel: "JPG to 50 KB",
    acceptedFileTypes: JPG_TYPES,
    acceptedMime: JPG_MIME,
    outputFormat: "jpeg",
    defaultTargetSize: 50,
    defaultTargetUnit: "KB",
    formatWord: "JPG",
    relatedSlugs: ["compress-jpg-to-20kb", "compress-jpg-to-100kb", "compress-passport-photo-to-50kb", "jpg-to-webp"],
  }),
  imgTool({
    slug: "compress-jpg-to-100kb",
    title: "Compress JPG to 100 KB",
    navLabel: "JPG to 100 KB",
    acceptedFileTypes: JPG_TYPES,
    acceptedMime: JPG_MIME,
    outputFormat: "jpeg",
    defaultTargetSize: 100,
    defaultTargetUnit: "KB",
    formatWord: "JPG",
    relatedSlugs: ["compress-jpg-to-50kb", "compress-image-to-100kb", "compress-png-to-100kb", "jpg-to-webp"],
  }),
  imgTool({
    slug: "compress-png-to-100kb",
    title: "Compress PNG to 100 KB",
    navLabel: "PNG to 100 KB",
    acceptedFileTypes: PNG_TYPES,
    acceptedMime: PNG_MIME,
    outputFormat: "png",
    defaultTargetSize: 100,
    defaultTargetUnit: "KB",
    formatWord: "PNG",
    relatedSlugs: ["compress-image-to-100kb", "png-to-jpg", "png-to-webp", "compress-image-to-200kb"],
    extraFaq: [
      {
        q: "Will my PNG's transparency be preserved?",
        a: "Yes. As long as the tool keeps the PNG format, transparent areas stay transparent. If quality-only compression cannot reach your target, dimensions are reduced before transparency is ever sacrificed.",
      },
    ],
  }),

  // ---------------- CUSTOM SIZE ----------------
  {
    slug: "compress-image-to-custom-size",
    title: "Compress Image to Custom Size",
    navLabel: "Custom Image Size",
    category: "image-compress",
    engine: "image-custom-size",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    defaultTargetSize: 100,
    defaultTargetUnit: "KB",
    allowCustomTarget: true,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Compress Image to Custom Size (KB or MB) | SizeSnap",
    metaDescription:
      "Enter any target size in KB or MB and compress your image to fit. Free, private, browser-based compression with instant preview.",
    intro:
      "Choose exactly how small you need your image — any value in KB or MB — and this tool will find the best quality that fits your target. Ideal when a form or portal asks for a size that doesn't match one of our preset tools.",
    contentSections: [
      {
        heading: "How to set a custom target",
        body: "Upload your image, switch the unit to KB or MB, and type the exact number you need. The tool validates your input (it must be greater than 1 KB and smaller than your original file) before compressing, so you can't accidentally request an impossible or meaningless target.",
      },
      {
        heading: "Why a custom target is useful",
        body: "Not every form uses round numbers like 100 KB or 1 MB — some ask for 75 KB, 150 KB, or 350 KB specifically. Rather than guessing with a preset and hoping it's close enough, you can match the exact limit and avoid a rejected upload.",
      },
      {
        heading: "How the compression works",
        body: "The engine performs an iterative search over JPEG/WebP quality settings, and reduces image dimensions only if quality reduction alone cannot reach your number. It always returns the highest-quality result that satisfies your target.",
      },
    ],
    tips: [
      "If your target is very close to the original size, expect only minor visible changes.",
      "For very aggressive targets, try a smaller or simpler source image for a cleaner result.",
      "Use MB for anything above roughly 1000 KB — it's easier to reason about for large targets.",
    ],
    faq: [
      { q: "What is the smallest size I can request?", a: "The minimum accepted target is greater than 1 KB. Extremely small targets on detailed photos will show visible compression artifacts." },
      { q: "Can I request a size larger than my original file?", a: "You can, but compression won't add data — if your target is larger than the original, the tool simply keeps the original file rather than pointlessly re-encoding it." },
      { q: "Is this tool private?", a: "Yes, the file is processed entirely in your browser and is never uploaded to a server." },
      { q: "Can I switch between KB and MB?", a: "Yes, use the unit dropdown next to the target size field at any time." },
    ],
    relatedSlugs: ["compress-image-to-200kb", "compress-image-to-500kb", "compress-pdf-to-custom-size", "image-resizer"],
  },

  // ---------------- PDF COMPRESSION ----------------
  ...([
    { slug: "compress-pdf-to-100kb", size: 100, unit: "KB" as const, use: "email attachments, application portals and forms with strict small-file limits" },
    { slug: "compress-pdf-to-200kb", size: 200, unit: "KB" as const, use: "resumes, short reports and scanned single-page documents" },
    { slug: "compress-pdf-to-500kb", size: 500, unit: "KB" as const, use: "multi-page reports, portfolios and forms with embedded images" },
    { slug: "compress-pdf-to-1mb", size: 1, unit: "MB" as const, use: "longer documents, brochures and files with several photos" },
    { slug: "compress-pdf-to-2mb", size: 2, unit: "MB" as const, use: "image-heavy presentations, scanned booklets and design proofs" },
    { slug: "compress-pdf-to-5mb", size: 5, unit: "MB" as const, use: "large multi-page documents that still need to fit common upload caps" },
  ] as const).map(({ slug, size, unit, use }) => {
    const label = unit === "MB" ? `${size} MB` : `${size} KB`;
    return {
      slug,
      title: `Compress PDF to ${label}`,
      navLabel: `PDF to ${label}`,
      category: "pdf-compress",
      engine: "pdf-target-size",
      acceptedFileTypes: [".pdf"],
      acceptedMime: ["application/pdf"],
      outputFormat: "pdf",
      defaultTargetSize: size,
      defaultTargetUnit: unit,
      allowCustomTarget: true,
      maxFileSizeMB: 20,
      clientSideOnly: false,
      seoTitle: `Compress PDF to ${label} Online Free | SizeSnap`,
      metaDescription: `Shrink your PDF to ${label} or less. Images are recompressed and unnecessary data is stripped while text and layout stay intact.`,
      intro: `Reduce your PDF to ${label} or less while keeping it fully usable — readable text, intact layout, and optimized embedded images. This is commonly needed for ${use}. Your file is processed securely and deleted automatically after compression.`,
      contentSections: [
        {
          heading: "How PDF compression works here",
          body: "The compressor optimizes embedded images (the biggest contributor to PDF size), removes redundant and unnecessary metadata, and rebuilds the file's internal object structure more efficiently. Text, fonts and page layout are preserved — only the data that can safely shrink is touched.",
        },
        {
          heading: "Why PDFs need server-side processing",
          body: "Browsers don't expose the low-level tools needed to recompress the images embedded inside a PDF or rebuild its object streams. To do this properly, your file is sent over a secure connection to our server for processing, held only in temporary storage, and automatically deleted immediately after your compressed file is returned.",
        },
        {
          heading: `Getting to ${label}`,
          body: `If ${label} can be reached without unacceptable quality loss, that's what you'll get. If the target is unrealistic for your document (for example, a scanned booklet with many high-resolution photos requested at ${label}), the tool tells you clearly and gives you the smallest version it could produce without corrupting the file.`,
        },
      ],
      tips: [
        "Scanned PDFs (photos of pages) compress much more than PDFs exported directly from Word or Google Docs, which are already efficient.",
        "If your PDF has very high-resolution images, consider whether you need that resolution before compressing.",
        "Text-only PDFs are usually already small — heavy compression targets are mainly useful for image-heavy files.",
      ],
      faq: [
        { q: `How do I compress a PDF to ${label}?`, a: `Upload your PDF, confirm the ${label} target, and press Compress. The tool optimizes embedded images and file structure automatically.` },
        { q: "Will compressing damage my PDF?", a: "No — the tool never corrupts a file to hit a target. If the requested size truly can't be reached safely, it says so and gives you the best achievable result instead." },
        { q: "Is my PDF uploaded to a server?", a: "Yes, PDF compression requires temporary server-side processing because browsers can't recompress embedded PDF images directly. Files are held only temporarily and deleted automatically after processing — see our Privacy Policy for details." },
        { q: "Will the text stay sharp?", a: "Yes. Compression targets embedded images and file structure; text and fonts are preserved as vector data and stay crisp." },
        { q: "What's the maximum PDF size I can upload?", a: "Up to 20 MB by default. Larger files may need to be split first." },
      ],
      relatedSlugs: ["compress-pdf-to-custom-size", "compress-pdf-to-500kb", "compress-pdf-to-1mb", "image-to-pdf"],
    } satisfies Tool;
  }),
  {
    slug: "compress-pdf-to-custom-size",
    title: "Compress PDF to Custom Size",
    navLabel: "Custom PDF Size",
    category: "pdf-compress",
    engine: "pdf-target-size",
    acceptedFileTypes: [".pdf"],
    acceptedMime: ["application/pdf"],
    outputFormat: "pdf",
    defaultTargetSize: 500,
    defaultTargetUnit: "KB",
    allowCustomTarget: true,
    maxFileSizeMB: 20,
    clientSideOnly: false,
    seoTitle: "Compress PDF to Custom Size (KB or MB) | SizeSnap",
    metaDescription: "Enter any target size and compress your PDF to fit. Images are optimized and unnecessary data removed while layout and text stay intact.",
    intro: "Set the exact KB or MB limit your form, portal or email requires and compress your PDF to match. Useful when the limit doesn't line up with a round preset.",
    contentSections: [
      { heading: "How to use it", body: "Upload your PDF, choose KB or MB, and enter your exact target. The tool validates that the value is realistic before processing." },
      { heading: "Processing method", body: "Your file is processed on our server (temporary storage, automatically deleted after processing) because embedded PDF image recompression isn't possible purely in the browser." },
      { heading: "When the target isn't achievable", body: "If your requested size would require corrupting the file or destroying its usability, the tool tells you plainly and returns the smallest safe result instead." },
    ],
    tips: ["Scanned documents compress far more than text-native PDFs.", "Very small targets on image-heavy PDFs will show visible artifacting in those images."],
    faq: [
      { q: "What's the minimum target size?", a: "Targets must be greater than 1 KB and smaller than your original file size." },
      { q: "Is my file stored permanently?", a: "No. Files are held only temporarily during processing and are automatically deleted afterward." },
    ],
    relatedSlugs: ["compress-pdf-to-500kb", "compress-pdf-to-1mb", "compress-pdf-to-100kb"],
  },

  // ---------------- IMAGE UTILITIES ----------------
  {
    slug: "image-resizer",
    title: "Image Resizer",
    navLabel: "Image Resizer",
    category: "image-resize",
    engine: "image-resize",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Free Online Image Resizer | SizeSnap",
    metaDescription: "Resize any image to exact pixel dimensions or a percentage scale, free and entirely in your browser.",
    intro: "Resize your image by exact pixel width and height, or by a percentage scale. Great for meeting dimension requirements before or after compressing to a target file size.",
    contentSections: [
      { heading: "How to resize", body: "Upload an image, enter a width and/or height in pixels (lock the aspect ratio to keep proportions), or use the percentage slider to scale down quickly, then download." },
      { heading: "Resizing vs. compressing", body: "Resizing changes an image's dimensions in pixels; compressing changes its file size in KB/MB. They're related — smaller dimensions usually mean a smaller file — but if you need a specific file size, use one of our compress-to-size tools instead, which adjust quality first and only resize as a last resort." },
      { heading: "Common uses", body: "Preparing images for a website, resizing photos to a platform's required dimensions, or shrinking an oversized photo before uploading it somewhere with pixel limits." },
    ],
    tips: ["Lock the aspect ratio unless you specifically need to stretch or crop the image.", "Resize before compressing if you need both a specific size in pixels and a specific file size."],
    faq: [
      { q: "Does resizing reduce file size too?", a: "Usually, yes — fewer pixels generally means a smaller file, though the exact size isn't guaranteed. Use a compress-to-size tool if you need an exact KB/MB target." },
      { q: "Will resizing distort my image?", a: "Not if you keep the aspect ratio locked, which is the default." },
      { q: "Is this processed on a server?", a: "No, resizing happens entirely in your browser using the Canvas API." },
    ],
    relatedSlugs: ["resize-image-to-custom-dimensions", "compress-image-to-custom-size", "passport-photo-resizer"],
  },
  {
    slug: "resize-image-to-custom-dimensions",
    title: "Resize Image to Custom Dimensions",
    navLabel: "Custom Dimensions",
    category: "image-resize",
    engine: "image-resize",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Resize Image to Custom Dimensions (Exact Pixels) | SizeSnap",
    metaDescription: "Type an exact width and height in pixels and resize any image to those precise dimensions for free.",
    intro: "Enter an exact width and height in pixels — for example 800x600 or 1080x1080 — and get your image resized to precisely those dimensions, with an option to preserve aspect ratio via smart cropping.",
    contentSections: [
      { heading: "Exact pixel control", body: "Unlike percentage scaling, this tool lets you type the precise width and height you need — useful for platforms, ad specs or forms that require a specific pixel size such as 600x800 for a passport photo or 1200x630 for a social share image." },
      { heading: "Handling aspect ratio mismatches", body: "If your requested dimensions don't match your image's original ratio, you can choose to stretch to fit or crop to fill so the subject stays centered without distortion." },
    ],
    tips: ["When exact dimensions are non-negotiable (e.g. an ID photo spec), use crop-to-fill rather than stretch to avoid a distorted look."],
    faq: [
      { q: "Can I enter dimensions in millimeters or inches?", a: "This tool works in pixels, which is what almost all digital forms require. If you need print dimensions, convert using your target DPI (e.g. 300 DPI: 2 inches = 600 pixels)." },
      { q: "Will my aspect ratio be distorted?", a: "Only if you choose 'stretch to fit'. Choose 'crop to fill' to keep proportions natural." },
    ],
    relatedSlugs: ["image-resizer", "passport-photo-resizer", "signature-resizer"],
  },
  {
    slug: "jpg-to-png",
    title: "JPG to PNG Converter",
    navLabel: "JPG to PNG",
    category: "image-convert",
    engine: "image-convert",
    acceptedFileTypes: JPG_TYPES,
    acceptedMime: JPG_MIME,
    outputFormat: "png",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert JPG to PNG Online Free | SizeSnap",
    metaDescription: "Convert JPG images to PNG format for free, in your browser, with no quality loss from the conversion itself.",
    intro: "Convert a JPG image to PNG format. PNG uses lossless compression, so this is useful when you need a format that supports transparency or want to avoid further JPEG artifacting in future edits.",
    contentSections: [
      { heading: "When to convert JPG to PNG", body: "Choose PNG when you need transparency support, when the image contains sharp text, line art or flat graphics that PNG compresses well, or when a platform specifically requires PNG uploads." },
      { heading: "What to expect", body: "The conversion itself doesn't add JPEG artifacts, but it also can't remove artifacts already present in your source JPG. PNG files are typically larger than JPGs of the same photo — if size matters, follow up with our Compress PNG to 100 KB tool." },
    ],
    tips: ["PNG is not automatically 'higher quality' than JPG for photos — it's just lossless from this point forward, and usually much larger."],
    faq: [
      { q: "Will converting to PNG improve image quality?", a: "No — it preserves whatever quality your JPG already has. It won't remove existing compression artifacts." },
      { q: "Will the file get bigger?", a: "Usually yes, since PNG is lossless and typically produces larger files than JPG for photographic images." },
    ],
    relatedSlugs: ["png-to-jpg", "compress-png-to-100kb", "png-to-webp"],
  },
  {
    slug: "png-to-jpg",
    title: "PNG to JPG Converter",
    navLabel: "PNG to JPG",
    category: "image-convert",
    engine: "image-convert",
    acceptedFileTypes: PNG_TYPES,
    acceptedMime: PNG_MIME,
    outputFormat: "jpeg",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert PNG to JPG Online Free | SizeSnap",
    metaDescription: "Convert PNG images to JPG for a much smaller file size, free and entirely in your browser.",
    intro: "Convert a PNG image to JPG format, typically shrinking the file size significantly. Transparent areas are filled with white since JPG doesn't support transparency.",
    contentSections: [
      { heading: "Why convert PNG to JPG", body: "PNG is lossless and often much larger than necessary for photographs. Converting to JPG applies efficient lossy compression, which is ideal when you need a smaller file and don't need transparency." },
      { heading: "What happens to transparency", body: "JPG has no transparency channel, so any transparent areas in your PNG are filled with a solid background color (white by default) during conversion." },
    ],
    tips: ["If your PNG relies on transparency, keep it as PNG or convert to WebP instead, which supports transparency."],
    faq: [
      { q: "What happens to transparent parts of my PNG?", a: "They are filled with a solid white background, since JPG doesn't support transparency." },
      { q: "How much smaller will the file be?", a: "It varies by image, but photographic PNGs often shrink by 50-90% when converted to JPG." },
    ],
    relatedSlugs: ["jpg-to-png", "compress-jpg-to-100kb", "webp-to-jpg"],
  },
  {
    slug: "webp-to-jpg",
    title: "WebP to JPG Converter",
    navLabel: "WebP to JPG",
    category: "image-convert",
    engine: "image-convert",
    acceptedFileTypes: [".webp"],
    acceptedMime: ["image/webp"],
    outputFormat: "jpeg",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert WebP to JPG Online Free | SizeSnap",
    metaDescription: "Convert WebP images to the more widely supported JPG format, free and in your browser.",
    intro: "Convert a WebP image to JPG for compatibility with older software, email clients and platforms that don't fully support WebP.",
    contentSections: [
      { heading: "Why convert from WebP", body: "WebP offers excellent compression but isn't universally supported by every app, printer or older device. Converting to JPG maximizes compatibility." },
      { heading: "What to expect", body: "Transparent areas in a WebP file are filled with white, since JPG has no transparency channel. Quality is preserved at a high level during conversion." },
    ],
    tips: ["If you need to keep transparency, convert to PNG instead."],
    faq: [
      { q: "Why can't I open a WebP file in some programs?", a: "WebP is a newer format and isn't supported everywhere yet. Converting to JPG solves this instantly." },
      { q: "Does converting reduce quality?", a: "Conversion uses a high JPG quality setting by default to minimize any visible difference." },
    ],
    relatedSlugs: ["jpg-to-webp", "png-to-jpg", "compress-jpg-to-100kb"],
  },
  {
    slug: "jpg-to-webp",
    title: "JPG to WebP Converter",
    navLabel: "JPG to WebP",
    category: "image-convert",
    engine: "image-convert",
    acceptedFileTypes: JPG_TYPES,
    acceptedMime: JPG_MIME,
    outputFormat: "webp",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert JPG to WebP Online Free | SizeSnap",
    metaDescription: "Convert JPG images to the modern, smaller WebP format for free, entirely in your browser.",
    intro: "Convert a JPG image to WebP, which typically produces 25-35% smaller files than JPG at equivalent visual quality — ideal for faster-loading websites.",
    contentSections: [
      { heading: "Why WebP", body: "WebP is a modern image format supported by all major browsers that generally compresses better than JPG at the same visual quality, which helps page load speed." },
      { heading: "Compatibility note", body: "WebP is widely supported today, but if you need maximum compatibility with very old software, keep a JPG version available too." },
    ],
    tips: ["WebP is a great default for website images where load speed matters."],
    faq: [
      { q: "Is WebP smaller than JPG?", a: "Typically yes, often by 25-35% at similar visual quality, though it varies by image." },
      { q: "Do all browsers support WebP?", a: "Yes, all current major browsers support WebP." },
    ],
    relatedSlugs: ["png-to-webp", "webp-to-jpg", "compress-jpg-to-100kb"],
  },
  {
    slug: "png-to-webp",
    title: "PNG to WebP Converter",
    navLabel: "PNG to WebP",
    category: "image-convert",
    engine: "image-convert",
    acceptedFileTypes: PNG_TYPES,
    acceptedMime: PNG_MIME,
    outputFormat: "webp",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert PNG to WebP Online Free | SizeSnap",
    metaDescription: "Convert PNG images to WebP for smaller files that still support transparency, free and in your browser.",
    intro: "Convert a PNG to WebP and keep transparency support while getting a noticeably smaller file than PNG typically produces.",
    contentSections: [
      { heading: "Best of both worlds", body: "WebP supports transparency like PNG but compresses far more efficiently, making it a strong replacement for PNG in most web use cases." },
      { heading: "When to still use PNG", body: "Keep PNG if you need maximum compatibility with very old tools or need guaranteed lossless output for archival purposes." },
    ],
    tips: ["Use WebP for website graphics with transparency to cut load times significantly."],
    faq: [
      { q: "Does WebP support transparency?", a: "Yes, WebP fully supports an alpha (transparency) channel, just like PNG." },
      { q: "Will the file be smaller than my PNG?", a: "In most cases yes, often substantially so." },
    ],
    relatedSlugs: ["jpg-to-webp", "jpg-to-png", "compress-png-to-100kb"],
  },
  {
    slug: "image-to-pdf",
    title: "Image to PDF Converter",
    navLabel: "Image to PDF",
    category: "image-to-pdf",
    engine: "image-to-pdf",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "pdf",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert Image to PDF Online Free | SizeSnap",
    metaDescription: "Combine one or more JPG, PNG or WebP images into a single PDF file, free and in your browser.",
    intro: "Turn one or more images into a single PDF document — each image becomes its own page, in the order you upload them. Works with JPG, PNG and WebP.",
    contentSections: [
      { heading: "How it works", body: "Upload your images (you can add several), reorder them if needed, and the tool combines them into one PDF file, sized to fit each image to the page." },
      { heading: "Common uses", body: "Combining scanned document photos into a single PDF for submission, turning a set of receipts into one file for expense reports, or preparing a portfolio as a single shareable PDF." },
    ],
    tips: ["Compress your images to a reasonable size before converting if the resulting PDF needs to meet a size limit — or use one of our Compress PDF tools afterward."],
    faq: [
      { q: "Can I combine multiple images into one PDF?", a: "Yes, upload as many images as you like and they'll be combined into a multi-page PDF in upload order." },
      { q: "Is this done in my browser?", a: "Yes, the PDF is assembled client-side and never leaves your device." },
    ],
    relatedSlugs: ["jpg-to-pdf", "png-to-pdf", "compress-pdf-to-500kb"],
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF Converter",
    navLabel: "JPG to PDF",
    category: "image-to-pdf",
    engine: "image-to-pdf",
    acceptedFileTypes: JPG_TYPES,
    acceptedMime: JPG_MIME,
    outputFormat: "pdf",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert JPG to PDF Online Free | SizeSnap",
    metaDescription: "Convert one or more JPG photos into a single PDF document, free and in your browser.",
    intro: "Convert your JPG photos into a single PDF document, one page per image, in the order you add them.",
    contentSections: [
      { heading: "How it works", body: "Upload one or more JPG files, arrange the order, and download a combined PDF." },
      { heading: "Typical uses", body: "Turning phone photos of documents into a single PDF for submission to schools, banks, or government portals that require PDF format." },
    ],
    tips: ["If the portal has a PDF size limit, compress the resulting file with our Compress PDF tools."],
    faq: [
      { q: "How many JPGs can I combine?", a: "There's no hard limit, but very large batches take longer to process and produce bigger files." },
    ],
    relatedSlugs: ["png-to-pdf", "image-to-pdf", "compress-pdf-to-500kb"],
  },
  {
    slug: "png-to-pdf",
    title: "PNG to PDF Converter",
    navLabel: "PNG to PDF",
    category: "image-to-pdf",
    engine: "image-to-pdf",
    acceptedFileTypes: PNG_TYPES,
    acceptedMime: PNG_MIME,
    outputFormat: "pdf",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Convert PNG to PDF Online Free | SizeSnap",
    metaDescription: "Convert one or more PNG images into a single PDF document, free and in your browser.",
    intro: "Convert PNG images into a single PDF document, one page per image, preserving transparency as a white background where needed.",
    contentSections: [
      { heading: "How it works", body: "Upload one or more PNG files, arrange them in order, and download a single combined PDF." },
      { heading: "Typical uses", body: "Combining screenshots, diagrams or scanned pages saved as PNG into one shareable document." },
    ],
    tips: ["Transparent PNG areas are placed on a white PDF page background."],
    faq: [
      { q: "Will transparency be preserved?", a: "PDF pages are opaque, so transparent PNG areas appear as white in the final document." },
    ],
    relatedSlugs: ["jpg-to-pdf", "image-to-pdf", "compress-pdf-to-500kb"],
  },

  // ---------------- APPLICATION TOOLS ----------------
  {
    slug: "signature-resizer",
    title: "Signature Image Resizer",
    navLabel: "Signature Resizer",
    category: "application",
    engine: "image-resize",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    allowCustomTarget: false,
    maxFileSizeMB: 10,
    clientSideOnly: true,
    seoTitle: "Signature Image Resizer Online Free | SizeSnap",
    metaDescription: "Resize a scanned or photographed signature to the exact pixel dimensions your form requires, free and in your browser.",
    intro: "Resize a scanned or photographed signature to exact pixel dimensions commonly required by bank forms, exam portals and job applications (for example 140x60 px).",
    contentSections: [
      { heading: "Getting a clean signature scan", body: "Sign on plain white paper with a dark pen, photograph or scan it in good light, then crop tightly before resizing for the cleanest result." },
      { heading: "Meeting exact requirements", body: "Many portals specify both pixel dimensions and a maximum file size for signatures. Resize first here, then use Compress Signature to 20 KB or 50 KB to meet a file size limit." },
    ],
    tips: ["Crop as close to the signature as possible before resizing to avoid empty margins eating into your size budget."],
    faq: [
      { q: "What size do banks usually require for signatures?", a: "It varies by institution, but 140x60 pixels or similar small dimensions with a file size under 20-50 KB is common. Always check your specific form's requirements." },
      { q: "Can I resize and compress in one step?", a: "This tool focuses on dimensions. For a file size target, follow up with Compress Signature to 20 KB or 50 KB." },
    ],
    relatedSlugs: ["compress-signature-to-20kb", "compress-signature-to-50kb", "image-resizer"],
  },
  {
    slug: "compress-signature-to-20kb",
    title: "Compress Signature to 20 KB",
    navLabel: "Signature to 20 KB",
    category: "application",
    engine: "image-target-size",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    defaultTargetSize: 20,
    defaultTargetUnit: "KB",
    allowCustomTarget: true,
    maxFileSizeMB: 10,
    clientSideOnly: true,
    seoTitle: "Compress Signature to 20 KB Online Free | SizeSnap",
    metaDescription: "Compress a scanned signature image to 20 KB or less for bank, exam and job application forms — free and private.",
    intro: "Compress a signature image to 20 KB or less — a common requirement for bank account forms, government exam applications and job portals. Because signatures are simple, high-contrast images, they compress cleanly even at very small sizes.",
    contentSections: [
      { heading: "Why signatures compress well at small sizes", body: "Unlike a detailed photograph, a signature is mostly flat white space with a few thin dark lines, so it holds up much better under aggressive compression than a typical photo would at the same target." },
      { heading: "Getting the best result", body: "Start from a well-lit, tightly cropped scan or photo on a plain background. If your form also specifies pixel dimensions, use the Signature Resizer first." },
    ],
    tips: ["Use a plain white or light background — busy backgrounds compress worse and look unprofessional.", "Scan in good lighting to avoid shadows that add unnecessary detail for the compressor to preserve."],
    faq: [
      { q: "Why does my form want such a small signature file?", a: "Signature fields are typically tiny UI elements, so portals cap the file size to keep forms fast and storage costs low." },
      { q: "Will the signature still be legible at 20 KB?", a: "Yes — because signatures are simple line art rather than detailed photos, they typically stay clearly legible even at very small file sizes." },
    ],
    relatedSlugs: ["compress-signature-to-50kb", "signature-resizer", "compress-image-to-20kb"],
  },
  {
    slug: "compress-signature-to-50kb",
    title: "Compress Signature to 50 KB",
    navLabel: "Signature to 50 KB",
    category: "application",
    engine: "image-target-size",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    defaultTargetSize: 50,
    defaultTargetUnit: "KB",
    allowCustomTarget: true,
    maxFileSizeMB: 10,
    clientSideOnly: true,
    seoTitle: "Compress Signature to 50 KB Online Free | SizeSnap",
    metaDescription: "Compress a scanned signature image to 50 KB or less for forms and portals that accept a slightly larger file — free and private.",
    intro: "Compress a signature image to 50 KB or less, the size some portals allow when 20 KB is too restrictive for a higher-resolution scan.",
    contentSections: [
      { heading: "More headroom than 20 KB", body: "50 KB gives noticeably more room than 20 KB, so a slightly larger or higher-resolution signature scan can be preserved with virtually no visible compression." },
      { heading: "Getting the best result", body: "As with any signature, a clean scan on a plain background compresses best. Check whether your form also requires specific pixel dimensions." },
    ],
    tips: ["If your portal accepts either 20 KB or 50 KB, the 50 KB option will generally look slightly cleaner."],
    faq: [
      { q: "Should I use 20 KB or 50 KB?", a: "Use whichever your specific form or portal requires. If both are acceptable, 50 KB will generally preserve slightly more detail." },
    ],
    relatedSlugs: ["compress-signature-to-20kb", "signature-resizer", "compress-image-to-50kb"],
  },
  {
    slug: "passport-photo-resizer",
    title: "Passport Photo Resizer",
    navLabel: "Passport Photo",
    category: "application",
    engine: "image-resize",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    allowCustomTarget: false,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Passport Photo Resizer Online Free | SizeSnap",
    metaDescription: "Resize a photo to common passport and visa photo dimensions, free and in your browser.",
    intro: "Resize a photo to common passport and ID photo dimensions, such as 2x2 inches (600x600 px at 300 DPI) for US passports or 51x51 mm for many other countries. Always confirm your destination country's exact current specification before submitting.",
    contentSections: [
      { heading: "Why exact dimensions matter", body: "Passport and visa authorities are strict about photo dimensions, head position and background. This tool handles the pixel dimensions; you are responsible for confirming the correct background, framing and head-size rules for your specific application." },
      { heading: "Common presets", body: "Use the dimension presets for frequently requested sizes, or enter custom pixel dimensions if your country's requirement differs. Pair this with our Compress Passport Photo tools if a file size limit also applies." },
    ],
    tips: ["Use a plain, evenly lit background as required by most passport photo rules.", "Double-check your destination country's current official requirements — they do change over time."],
    faq: [
      { q: "What size should a passport photo be?", a: "It depends on the country. The US typically requires 2x2 inches (600x600 px at 300 DPI); many other countries require 35x45 mm or 51x51 mm. Always confirm current requirements with the issuing authority." },
      { q: "Does this tool check background or framing rules?", a: "No — it resizes to the dimensions you specify. Background color, head position and lighting are your responsibility to get right before or after resizing." },
    ],
    relatedSlugs: ["compress-passport-photo-to-50kb", "compress-passport-photo-to-100kb", "resize-image-to-custom-dimensions"],
  },
  {
    slug: "compress-passport-photo-to-50kb",
    title: "Compress Passport Photo to 50 KB",
    navLabel: "Passport Photo to 50 KB",
    category: "application",
    engine: "image-target-size",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    defaultTargetSize: 50,
    defaultTargetUnit: "KB",
    allowCustomTarget: true,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Compress Passport Photo to 50 KB Online Free | SizeSnap",
    metaDescription: "Compress a passport or ID photo to 50 KB or less while keeping facial detail as clear as possible — free and private.",
    intro: "Compress a passport or ID photo to 50 KB or less, a common limit on visa and government portals. Facial photos need to stay clear enough for identification, so the compressor prioritizes keeping detail in the face.",
    contentSections: [
      { heading: "Balancing size and clarity", body: "Passport photos are judged on clarity, since they're used for identification. The compressor uses the highest quality setting that fits your target, so features stay as recognizable as possible even under a strict 50 KB limit." },
      { heading: "Before you compress", body: "Make sure your photo already meets your destination's dimension requirements using the Passport Photo Resizer — compress after resizing, not before, for the most predictable result." },
    ],
    tips: ["Resize to the correct pixel dimensions first, then compress to the file size limit.", "Use a high-resolution, well-lit original for the clearest result at 50 KB."],
    faq: [
      { q: "In what order should I resize and compress?", a: "Resize to the required pixel dimensions first, then compress to your file size limit — doing it in this order gives the most predictable, accurate result." },
      { q: "Will my face still be clear at 50 KB?", a: "Yes for a typical passport-sized photo — 50 KB is generally enough headroom to keep facial features clearly recognizable." },
    ],
    relatedSlugs: ["compress-passport-photo-to-100kb", "passport-photo-resizer", "compress-image-to-50kb"],
  },
  {
    slug: "compress-passport-photo-to-100kb",
    title: "Compress Passport Photo to 100 KB",
    navLabel: "Passport Photo to 100 KB",
    category: "application",
    engine: "image-target-size",
    acceptedFileTypes: IMG_TYPES,
    acceptedMime: IMG_MIME,
    outputFormat: "keep",
    defaultTargetSize: 100,
    defaultTargetUnit: "KB",
    allowCustomTarget: true,
    maxFileSizeMB: 20,
    clientSideOnly: true,
    seoTitle: "Compress Passport Photo to 100 KB Online Free | SizeSnap",
    metaDescription: "Compress a passport or ID photo to 100 KB or less with minimal visible quality loss — free and private.",
    intro: "Compress a passport or ID photo to 100 KB or less. This is a more generous limit than 50 KB, so quality loss is typically minimal even for high-resolution originals.",
    contentSections: [
      { heading: "More headroom for clarity", body: "At 100 KB, most passport photos compress with little to no visible change, keeping facial features sharp and clear for identification purposes." },
      { heading: "Before you compress", body: "Resize to the correct pixel dimensions for your destination country first using the Passport Photo Resizer, then compress to the file size limit." },
    ],
    tips: ["Resize before compressing for the most predictable result.", "A well-lit, in-focus original photo will give the cleanest result."],
    faq: [
      { q: "Is 100 KB enough for a clear passport photo?", a: "Yes, 100 KB typically leaves enough headroom for minimal to no visible quality loss on a standard passport photo." },
    ],
    relatedSlugs: ["compress-passport-photo-to-50kb", "passport-photo-resizer", "compress-image-to-100kb"],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: Tool["category"]): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function getRelatedTools(tool: Tool): Tool[] {
  return tool.relatedSlugs
    .map((slug) => getToolBySlug(slug))
    .filter((t): t is Tool => Boolean(t));
}
